### ISSUE TITLE
Pipes RF24_RX_ADDR.P2 and above not working

### ISSUE THREAD

**Issue by Lennart99** [bjarne-hansen/py-nrf24#17]
The Pipes RF24_RX_ADDR.P2 and above seem to not be working, If I doe anything wrong, please tell.

Raspberry Pi code:
```
import pigpio
import nrf24
import struct

slaves = [[nrf24.RF24_RX_ADDR.P0, 0x00], [nrf24.RF24_RX_ADDR.P1, 0x01], [nrf24.RF24_RX_ADDR.P2, 0x02], [nrf24.RF24_RX_ADDR.P3, 0x03]]

# Connect to Raspberry Pi
pi = pigpio.pi()

# Set up NRF24L01 module for reading.
radio = nrf24.NRF24(pi, ce=22, data_rate=nrf24.RF24_DATA_RATE.RATE_250KBPS, payload_size=nrf24.RF24_PAYLOAD.from_value(8))
radio.set_pa_level(nrf24.RF24_PA.LOW)
for slave in slaves:
    radio.open_reading_pipe(slave[0], [slave[1], 0, 0, 0, 0])

while True:
    while radio.data_ready(): 
        # Get pipe, payload.
        pipe = radio.data_pipe()
        payload = radio.get_payload()

        # Convert data to hex.
        hex = ':'.join(f'{i:02x}' for i in payload)
        
        print(f'Data received on pipe {pipe}: {hex}')
        
        # Unpack protocol, temperature, and humidity.
        (id, data) = struct.unpack('<ii', payload)

        # Report
        print(f'pipe: {pipe}, id: {id}, data: {data}')```
```
arduino code:

```
/*
* 
* Library: TMRh20/RF24, https://github.com/tmrh20/RF24/
*/
#include <SPI.h>
#include <nRF24L01.h>
#include <RF24.h>

struct Package {
  long id;
  long data;
};

RF24 radio(7, 8); // CE, CSN

const uint64_t address = 0x00LL; // every 'slave' will get a different address

void setup() {

  radio.begin();
  radio.enableDynamicPayloads();
  radio.setPayloadSize(sizeof(Package));
  radio.setAutoAck(true);
  radio.setPALevel(RF24_PA_LOW);
  radio.setDataRate(RF24_250KBPS);
  radio.openWritingPipe(address);

  radio.stopListening();
}

int data = 0;
void loop() {
  Package pack;
  pack.id = 1;
  pack.data = data;
  
 radio.write(&pack, sizeof(Package));

  data ++;

  delay(1000);
}
```

When setting the address in the arduino code to 0 or 1, the data is received normally, but when the address is set to 2 or 3, the raspberry pi receives nothing.

Please let me know if this is a bug or if i am doing it wrong

**Comment by bjarne-hansen** [comment]
Dear Lennart,

_I am quite sure that the library works for several pipes, as I have data collection gateways using 2 NRF24L01 modules with 4 receivers on each module (8 sending sensors in all)._

From looking at you code, the python part seems OK.  You can use a string, an array of bytes, or an integer when specifying the address. However, it can be confusing sometimes, as the "endianess" of the system you are on determines the byte order of things.

I know for sure that a python program on a raspberry with addresses "1SOIL", "2SOIL", "3SOIL", "4SOIL" works with soil moisture sensors driven by Arduinos using a sender definition like this: byte sensor_tx[6] = "1SOIL"; 

I can't remember the details on top of my head, but I think what tricks you is byte array on the receiving side and const uint64_t address = 0x00LL; on the Arduino side ... (endianess). 

I may add this type of information to the README.md if I find my notes from the day I experimented with that.

DISCLAIMER: I have not debugged your code, so there may be other reasons for you not sending/receiving data correctly.

//bjarne

**Comment by Lennart99** [comment]
Dear Bjarne,

I am now using the same addresses you told, "1SOIL", "2SOIL", "3SOIL", "4SOIL", set up in this manner:
```
slaves = [[nrf24.RF24_RX_ADDR.P1, "1SOIL"], [nrf24.RF24_RX_ADDR.P2, "2SOIL"], [nrf24.RF24_RX_ADDR.P3, "3SOIL"], [nrf24.RF24_RX_ADDR.P4, "4SOIL"]]
(...)
for slave in slaves:
    radio.open_reading_pipe(slave[0], slave[1])
```

In the arduino code I just changed the address to 
```
const byte address[6] = "1SOIL";
```
and then it works, but when I change it to 2SOIL, 3SOIL or 4SOIL it does not.

Do you have any idea what library you use in your arduino code? The library seems simular to what I use but maybe it a bit different in the back?

I myself am using the RF24 library from TMRh20 (this one: https://tmrh20.github.io/RF24/)

I have got this to work with C++ on the raspberry pi now, but preferably I would like to use python instead.

Please let me know if you have any ideas
