### ISSUE TITLE
Using with an arduino as receiver

### ISSUE THREAD

**Issue by Tarkhrodd** [bjarne-hansen/py-nrf24#37]
Hello,
I have trouble using this library  to use an arduino as a receiver. Does anyone have some sample code or hints ?
Thanks

**Comment by bjarne-hansen** [comment]
@Tarkhrodd

https://howtomechatronics.com/tutorials/arduino/arduino-wireless-communication-nrf24l01-tutorial/
Not sure what your problem is, but byte order is one thing that comes to mind when communicating between Arduino and Raspberry (address of the receiver)

//bjarne
